export const metadata = {
    title: "Welcome to home Page",
    description: "Generated by create next app",
  };
  
  export default function Layout({ children }) {
    return (
        <div>
          {children}
        </div>
    );
  }