
export const metadata = {
    title: "Eldeco Group",
    description: "Generated by create next app",
  };

export default function Layout({children}){
    return(
        <div>
            {children}
        </div>
    )
}