
export const metadata = {
    title: "Eldeco Group",
    description: "Generated by create next app",
  };

export default function Layout({children}){
    return(
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}